---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ice-driver-daemon
subjects:
- kind: ServiceAccount
  name: ice-driver-daemon
roleRef:
  kind: Role
  name: ice-driver-daemon
  apiGroup: rbac.authorization.k8s.io
