apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-master-server
  namespace: openshift-operators
spec:
  operand:
    image: 'quay.io/openshift/origin-node-feature-discovery:4.7'
    imagePullPolicy: Always
    namespace: node-feature-discovery-operator
  workerConfig:
    configData: |
      sources:
        pci:
          deviceLabelFields:
            - "vendor"
            - "device"
          deviceClassWhitelist:
            - "0200"
            - "03"
            - "12"
        custom:
          - name: "ddp-capable.pci.feature"
            matchOn:
              - pciId:
                vendor: ["8086"]
                device: ["1592"]
