kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ice-ddp-pkg-container
  namespace: kmod-ice
  labels:
    app: ice-ddp-pkg-container
spec:
  lookupPolicy:
    local: true
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ice-ddp-pkg-build
  namespace: kmod-ice
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  output:
    to:
      kind: ImageStreamTag
      name: "ice-ddp-pkg-container:1.3.2"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      pullSecret:
        name: default-dockercfg-9hdp6
      buildArgs:
        - name: KMOD_DDP_PACKAGE
          value: https://downloadmirror.intel.com/30335/eng/ice_comms-1.3.24.0.zip
        - name: CONTAINER_IMAGE_URL
          value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:abf3de7de03664ff637ab6ae9fb73a7fcff8ac59b2c47862eeffac14fa80da31

  postCommit: {}
  source:
    dockerfile: >
      FROM registry.access.redhat.com/ubi8/ubi-minimal
 
      RUN microdnf install -y wget unzip
    
      ARG KMOD_DDP_PACKAGE

      RUN wget "$KMOD_DDP_PACKAGE"

      RUN package_zip_file=$(basename "$KMOD_DDP_PACKAGE") && \
        mkdir -p "/var/lib/firmware/updates/intel/ice/ddp/" && \
        unzip "$package_zip_file" -d "/var/lib/firmware/updates/intel/ice/ddp/" && \
        rm -fv "/var/lib/firmware/updates/intel/ice/ddp/ice.pkg" && \
        package_file="${package_zip_file%.zip}.pkg" && \
        mv -f "/var/lib/firmware/updates/intel/ice/ddp/$package_file" "/var/lib/firmware/updates/intel/ice/ddp/ice.pkg"
    secrets:
      - secret:
          name: entitlement
  triggers:
    - type: ConfigChange
  runPolicy: Serial
