kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ice-kmod-driver-container
  namespace: kmod-ice
  labels:
    app: ice-kmod-driver-container
spec:
  lookupPolicy:
    local: true
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ice-kmod-driver-build
  namespace: kmod-ice
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  output:
    to:
      kind: ImageStreamTag
      name: "ice-kmod-driver-container:1.3.2"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      pullSecret:
        name: default-dockercfg-9hdp6
      buildArgs:
        - name: KMODVER
          value: 1.3.2
        - name: KMOD_DDP_PACKAGE
          value: https://downloadmirror.intel.com/30335/eng/ice_comms-1.3.24.0.zip
        - name: CONTAINER_IMAGE_URL
          value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:abf3de7de03664ff637ab6ae9fb73a7fcff8ac59b2c47862eeffac14fa80da31

  postCommit: {}
  source:
    type: Git
    dockerfile: >
      FROM $CONTAINER_IMAGE_URL

      WORKDIR /build/

      RUN yum -y install rpm-build gcc

      # Expecting kmod software version as an input to the build 

      ARG KMODVER
      ARG KMOD_DDP_PACKAGE

      RUN wget
      "https://sourceforge.net/projects/e1000/files/ice%20stable/$KMODVER/ice-$KMODVER.tar.gz"
      \
        && rpmbuild --define "_topdir `pwd`" -tb ice-$KMODVER.tar.gz 

      # Prep and build the module  

      RUN dnf install -y RPMS/x86_64/ice-$KMODVER-1.x86_64.rpm 

      # Add the helper tools 

      WORKDIR /root/kvc-ice-kmod

      ADD Makefile . 

      ADD ice-kmod-lib.sh . 

      ADD ice-kmod-wrapper.sh . 

      ADD ice-kmod.conf .

      RUN mkdir -p /usr/lib/kvc/

      RUN mkdir -p /etc/kvc/

      RUN make install

      RUN systemctl enable kmods-via-containers@ice-kmod

      RUN wget "$KMOD_DDP_PACKAGE"

      RUN package_zip_file=$(basename "$KMOD_DDP_PACKAGE") && \
        mkdir -p "/var/lib/firmware/updates/intel/ice/ddp/" && \
        unzip "$package_zip_file" -d "/var/lib/firmware/updates/intel/ice/ddp/" && \
        rm -fv "/var/lib/firmware/updates/intel/ice/ddp/ice.pkg" && \
        package_file="${package_zip_file%.zip}.pkg" && \
        mv -f "/var/lib/firmware/updates/intel/ice/ddp/$package_file" "/var/lib/firmware/updates/intel/ice/ddp/ice.pkg"
    git:
      uri: "https://github.com/atyronesmith/kvc-ice-kmod.git"
      ref: main
    secrets:
      - secret:
          name: entitlement
  triggers:
    - type: ConfigChange
  runPolicy: Serial
