apiVersion: v1
kind: ServiceAccount
metadata:
  name: kmod-driver-container
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kmod-driver-container
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kmod-driver-container
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kmod-driver-container
subjects:
  - kind: ServiceAccount
    name: kmod-driver-container
userNames:
  - system:serviceaccount:kmod-ice:kmod-driver-container
